environment:
  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3

platform:
  - x64

build: off

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - "conda create -q -n test-environment python=%PYTHON_VERSION%"
  - activate test-environment
  - python -m pip install --upgrade pip pytest nbval .

test_script:
  - python -c "import joommfutil as j; import sys; sys.exit(j.test())"
  - python -m pytest --nbval docs\ipynb\*.ipynb
  - python -m pytest --doctest-modules --ignore=joommfutil\tests joommfutil