environment:
  matrix:
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3

platform:
  - x64

build: off

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - cmd: python -m pip install pytest .

test_script:
  - cmd: python -m pytest -v

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.